# [作業目標]
- 仿造範例的 One Hot Encoding, 將指定的資料進行編碼

# [作業重點]
- 將 sub_train 進行 One Hot Encoding 編碼 (In[4], Out[4])

In [15]:
import os
import numpy as np
import pandas as pd

In [16]:
# 設定 data_path, 並讀取 app_train
dir_data = './data/'
f_app_train = os.path.join(dir_data, 'application_train.csv')
app_train = pd.read_csv(f_app_train)

## 作業
將下列部分資料片段 sub_train 使用 One Hot encoding, 並觀察轉換前後的欄位數量 (使用 shape) 與欄位名稱 (使用 head) 變化

In [17]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()

(307511, 1)

  WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [18]:
"""
Your Code Here
"""
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
data_le=pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
data_le['WEEKDAY_APPR_PROCESS_START'] = labelencoder.fit_transform(data_le['WEEKDAY_APPR_PROCESS_START'])
print(data_le.shape)
data_le.head()
data_le

(307511, 1)

        WEEKDAY_APPR_PROCESS_START
0                                6
1                                1
2                                1
3                                6
4                                4
5                                6
6                                3
7                                1
8                                6
9                                4
10                               2
11                               0
12                               0
13                               4
14                               1
15                               2
16                               4
17                               1
18                               0
19                               1
20                               0
21                               1
22                               4
23                               0
24                               4
25                               2
26                               1
27                               2
28                               6
29                               5
...                            ...
307481                           0
307482                           4
307483                           1
307484                           1
307485                           2
307486                           2
307487                           6
307488                           6
307489                           0
307490                           2
307491                           2
307492                           0
307493                           1
307494                           1
307495                           6
307496                           4
307497                           4
307498                           1
307499                           5
307500                           0
307501                           6
307502                           1
307503                           2
307504                           6
307505                           1
307506                           4
307507                           1
307508                           4
307509                           6
307510                           4

[307511 rows x 1 columns]

In [19]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
data_str_ohe=onehotencoder.fit_transform(data_le).toarray()
pd.DataFrame(data_str_ohe)

C:\Users\Dennis\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Dennis\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

          0    1    2    3    4    5    6
0       0.0  0.0  0.0  0.0  0.0  0.0  1.0
1       0.0  1.0  0.0  0.0  0.0  0.0  0.0
2       0.0  1.0  0.0  0.0  0.0  0.0  0.0
3       0.0  0.0  0.0  0.0  0.0  0.0  1.0
4       0.0  0.0  0.0  0.0  1.0  0.0  0.0
5       0.0  0.0  0.0  0.0  0.0  0.0  1.0
6       0.0  0.0  0.0  1.0  0.0  0.0  0.0
7       0.0  1.0  0.0  0.0  0.0  0.0  0.0
8       0.0  0.0  0.0  0.0  0.0  0.0  1.0
9       0.0  0.0  0.0  0.0  1.0  0.0  0.0
10      0.0  0.0  1.0  0.0  0.0  0.0  0.0
11      1.0  0.0  0.0  0.0  0.0  0.0  0.0
12      1.0  0.0  0.0  0.0  0.0  0.0  0.0
13      0.0  0.0  0.0  0.0  1.0  0.0  0.0
14      0.0  1.0  0.0  0.0  0.0  0.0  0.0
15      0.0  0.0  1.0  0.0  0.0  0.0  0.0
16      0.0  0.0  0.0  0.0  1.0  0.0  0.0
17      0.0  1.0  0.0  0.0  0.0  0.0  0.0
18      1.0  0.0  0.0  0.0  0.0  0.0  0.0
19      0.0  1.0  0.0  0.0  0.0  0.0  0.0
20      1.0  0.0  0.0  0.0  0.0  0.0  0.0
21      0.0  1.0  0.0  0.0  0.0  0.0  0.0
22      0.0  0.0  0.0  0.0  1.0  0.0  0.0
23      1.0  0.0  0.0  0.0  0.0  0.0  0.0
24      0.0  0.0  0.0  0.0  1.0  0.0  0.0
25      0.0  0.0  1.0  0.0  0.0  0.0  0.0
26      0.0  1.0  0.0  0.0  0.0  0.0  0.0
27      0.0  0.0  1.0  0.0  0.0  0.0  0.0
28      0.0  0.0  0.0  0.0  0.0  0.0  1.0
29      0.0  0.0  0.0  0.0  0.0  1.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
307481  1.0  0.0  0.0  0.0  0.0  0.0  0.0
307482  0.0  0.0  0.0  0.0  1.0  0.0  0.0
307483  0.0  1.0  0.0  0.0  0.0  0.0  0.0
307484  0.0  1.0  0.0  0.0  0.0  0.0  0.0
307485  0.0  0.0  1.0  0.0  0.0  0.0  0.0
307486  0.0  0.0  1.0  0.0  0.0  0.0  0.0
307487  0.0  0.0  0.0  0.0  0.0  0.0  1.0
307488  0.0  0.0  0.0  0.0  0.0  0.0  1.0
307489  1.0  0.0  0.0  0.0  0.0  0.0  0.0
307490  0.0  0.0  1.0  0.0  0.0  0.0  0.0
307491  0.0  0.0  1.0  0.0  0.0  0.0  0.0
307492  1.0  0.0  0.0  0.0  0.0  0.0  0.0
307493  0.0  1.0  0.0  0.0  0.0  0.0  0.0
307494  0.0  1.0  0.0  0.0  0.0  0.0  0.0
307495  0.0  0.0  0.0  0.0  0.0  0.0  1.0
307496  0.0  0.0  0.0  0.0  1.0  0.0  0.0
307497  0.0  0.0  0.0  0.0  1.0  0.0  0.0
307498  0.0  1.0  0.0  0.0  0.0  0.0  0.0
307499  0.0  0.0  0.0  0.0  0.0  1.0  0.0
307500  1.0  0.0  0.0  0.0  0.0  0.0  0.0
307501  0.0  0.0  0.0  0.0  0.0  0.0  1.0
307502  0.0  1.0  0.0  0.0  0.0  0.0  0.0
307503  0.0  0.0  1.0  0.0  0.0  0.0  0.0
307504  0.0  0.0  0.0  0.0  0.0  0.0  1.0
307505  0.0  1.0  0.0  0.0  0.0  0.0  0.0
307506  0.0  0.0  0.0  0.0  1.0  0.0  0.0
307507  0.0  1.0  0.0  0.0  0.0  0.0  0.0
307508  0.0  0.0  0.0  0.0  1.0  0.0  0.0
307509  0.0  0.0  0.0  0.0  0.0  0.0  1.0
307510  0.0  0.0  0.0  0.0  1.0  0.0  0.0

[307511 rows x 7 columns]

In [20]:
app_train = pd.get_dummies(sub_train)

In [21]:
print(app_train.shape)
app_train.head()

(307511, 7)

,WEEKDAY_APPR_PROCESS_START_FRIDAY,WEEKDAY_APPR_PROCESS_START_MONDAY,WEEKDAY_APPR_PROCESS_START_SATURDAY,WEEKDAY_APPR_PROCESS_START_SUNDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY
0,0,0,0,0,0,0,1
1,0,1,0,0,0,0,0
2,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1
4,0,0,0,0,1,0,0